UI/Controllers/InventarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using DTO;

namespace UI.Controllers
{
    public class InventarioController : BaseController
    {
        // GET: Inventario
        public ActionResult Index()
        {
            if (Seguridad() == null)
                return RedirectToAction("Login", "Login");

            return View(new InventarioBLL().TodoInventario());
        }

        public ActionResult Movimiento(int id)
        {
            if (Seguridad() == null)
                return RedirectToAction("Login", "Login");

            ViewBag.Tipos = new CatalogoBLL().CatalogoTipos();
            return View(new InventarioBLL().InventarioByID(id));
        }

        public ActionResult Historial(int id)
        {
            if (Seguridad() == null)
                return RedirectToAction("Login", "Login");

            ViewBag.Tipos = new CatalogoBLL().CatalogoTipos();
            return View(new InventarioBLL().SelectHistorial(id));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RealizarMovimiento(MovimientoDTO data)
        {
            if (Seguridad() == null)
                return Json(new Response() { Code = 400, Message = "Su sesión expiro, por favor ingrese de nuevo" });
            
            if(data == null )
                return Json(new Response() { Code = 500, Message = "Bad request" });

            if (data.CantidadMovimiento == 0)
                return Json(new Response() { Code = 500, Message = "Cantidad no válida." });

            if (data.InventarioID == 0)
                return Json(new Response() { Code = 500, Message = "Inventario no valido." });

            UsuarioDTO user = Seguridad();

            return Json(new InventarioBLL().RealizarMovimiento(data,user.UsuarioID));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult SeleccionarTodoInventario()
        {
            if (Seguridad() == null)
                return Json(new Response() { Code = 400, Message = "Su sesión expiro, por favor ingrese de nuevo" });
          
            UsuarioDTO user = Seguridad();

            return Json(new InventarioBLL().TodoInventario());
        }
    }
}

UI/Controllers/LoginController.cs
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;

namespace UI.Controllers
{
    public class LoginController : BaseController
    {
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult LoginUser(LoginDTO data)
        {
            if (data == null) return Json(new Response() { Code = 500, Message = "Bad Request" });

            if (string.IsNullOrEmpty(data.Password))
                return Json(new Response() { Code = 500, Message = "Contraseña incorrecta." });
            if (data.Password.Length <= 8)
                return Json(new Response() { Code = 500, Message = "Contraseña incorrecta, debe tener mas de 8 caracteres" });

            if (string.IsNullOrEmpty(data.Correo))
                return Json(new Response() { Code = 500, Message = "Correo no válido." });

            if (!UtilidadesBLL.EsCorreoValido(data.Correo))
                return Json(new Response() { Code = 500, Message = "Correo no válido." });

            Response loginResponse = new UsuarioBLL().Login(data);
            if (loginResponse.Code == 200)
            {
                Session["user"] = loginResponse.Items;
            }
            return Json(loginResponse);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RegistroUser(RegistroDTO data)
        {
            if (data == null) return Json(new Response() { Code = 500, Message = "Bad Request" });
            
            if(string.IsNullOrEmpty(data.Password))
                return Json(new Response() { Code = 500, Message = "Contraseña incorrecta." });
            if (data.Password.Length <= 8)
                return Json(new Response() { Code = 500, Message = "Contraseña incorrecta, debe tener mas de 8 caracteres" });
            if(data.Password != data.ValidaPassword)
                return Json(new Response() { Code = 500, Message = "Las contraseñas no coinciden." });

            if (string.IsNullOrEmpty(data.Correo))
                return Json(new Response() { Code = 500, Message = "Correo no válido." });

            if (!UtilidadesBLL.EsCorreoValido(data.Correo))
                return Json(new Response() { Code = 500, Message = "Correo no válido." });

            Response loginResponse = new UsuarioBLL().Registrar(data);

            if (loginResponse.Code == 200)
            {
                Session["user"] = loginResponse.Items;
            }
            return Json(loginResponse);
        }

        public ActionResult NoAcceso(){
            return View();
        }

        public ActionResult Perfil(){

            if (Seguridad() == null)
                return RedirectToAction("Login");
            UsuarioDTO user = Seguridad();

            return View(new UsuarioBLL().SelectById(user.UsuarioID));
        }


        public ActionResult LogOut(){
            Session["user"] = null;
            return RedirectToAction("Login");
        }

    }
}

UI/Controllers/MaterialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using DTO;
namespace UI.Controllers
{
    public class MaterialController : BaseController
    {
        // GET: Material
        public ActionResult Index()
        {
            if (Seguridad() == null)
                return RedirectToAction("Login", "Login");

            UsuarioDTO user = Seguridad();
            if (user.RolId != 1)
                return RedirectToAction("NoAcceso", "Login");

            return View(new MaterialBLL().Todos());
        }

        public ActionResult AddMaterial()
        {
            if (Seguridad() == null)
                return RedirectToAction("Login", "Login");

            return View();
        }

        public ActionResult EditMaterial(int id)
        {
            if (Seguridad() == null)
                return RedirectToAction("Login", "Login");

            return View(new MaterialBLL().SelectById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RegistrarMaterial(MaterialDTO data){
            if (Seguridad() == null)
                return Json(new Response() { Code = 400, Message = "Su sesión expiro, por favor ingrese de nuevo" });

            if(data == null)
                return Json(new Response() { Code = 500, Message = "Bad request" });

            if(string.IsNullOrEmpty(data.Codigo))
                return Json(new Response() { Code = 500, Message = "Bad request" });

            if (string.IsNullOrEmpty(data.Nombre))
                return Json(new Response() { Code = 500, Message = "Bad request" });

            UsuarioDTO user = Seguridad();

            return Json(new MaterialBLL().Registrar(data, user.UsuarioID));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult EliminarMaterial(MaterialDTO data)
        {
            if (Seguridad() == null)
                return Json(new Response() { Code = 400, Message = "Su sesión expiro, por favor ingrese de nuevo" });

            if (data == null)
                return Json(new Response() { Code = 500, Message = "Bad request" });

            if (data.MaterialID == 0)
                return Json(new Response() { Code = 500, Message = "Bad request" });

            UsuarioDTO user = Seguridad();

            return Json(new MaterialBLL().Eliminar(data, user.UsuarioID));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult EditarMaterial(MaterialDTO data)
        {
            if (Seguridad() == null)
                return Json(new Response() { Code = 400, Message = "Su sesión expiro, por favor ingrese de nuevo" });

            if (data.MaterialID == 0)
                return Json(new Response() { Code = 500, Message = "Bad request" });

            if(data == null)
                return Json(new Response() { Code = 500, Message = "Bad request" });

            if (string.IsNullOrEmpty(data.Codigo))
                return Json(new Response() { Code = 500, Message = "Bad request" });

            if (string.IsNullOrEmpty(data.Nombre))
                return Json(new Response() { Code = 500, Message = "Bad request" });

            UsuarioDTO user = Seguridad();

            return Json(new MaterialBLL().Editar(data, user.UsuarioID));
        }
    }
}

UI/Controllers/ReporteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using DTO;

namespace UI.Controllers
{
    public class ReporteController : BaseController
    {
        // GET: Reporte
        public ActionResult Index()
        {
            if (Seguridad() == null)
                return RedirectToAction("Login", "Login");

            UsuarioDTO user = Seguridad();
            if (user.RolId != 1)
                return RedirectToAction("NoAcceso", "Login");

            return View(new InventarioBLL().TodoHistorial());
        }

        public ActionResult Dashboard()
        {
            if (Seguridad() == null)
                return RedirectToAction("Login", "Login");

            return View();
        }
    }
}

UI/Controllers/UsuarioController.cs
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;

namespace UI.Controllers
{
    public class UsuarioController : BaseController
    {
        // GET: Usuario
        public ActionResult Index()
        {
            if (Seguridad() == null)
                return RedirectToAction("Login", "Login");

            UsuarioDTO user = Seguridad();
            if(user.RolId != 1)
                return RedirectToAction("NoAcceso","Login");

            return View(new UsuarioBLL().Todos());
        }

        public ActionResult AddUsuario()
        {
            if (Seguridad() == null)
                return RedirectToAction("Login", "Login");

            UsuarioDTO user = Seguridad();
            if (user.RolId != 1)
                return RedirectToAction("NoAcceso", "Login");

            ViewBag.Roles = new CatalogoBLL().CatalogoRoles();
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Activacion(UsuarioDTO data){
            if (Seguridad() == null)
                return Json(new Response() { Code = 400, Message = "Su sesión expiro, por favor ingrese de nuevo" });

            UsuarioDTO user = Seguridad();

            return Json(new UsuarioBLL().ActivaDesactiva(data, user.UsuarioID));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult EliminarUsuario(UsuarioDTO data)
        {
            if (Seguridad() == null)
                return Json(new Response() { Code = 400, Message = "Su sesión expiro, por favor ingrese de nuevo" });

            if(data == null)
                return Json(new Response() { Code = (int)UtilidadesBLL.EstadoAplicacion.ServerError, Message = "Bad request" });

            UsuarioDTO user = Seguridad();

            return Json(new UsuarioBLL().Eliminar(data, user.UsuarioID));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult AdicionarUsuario(UsuarioDTO data)
        {
            if (Seguridad() == null)
                return Json(new Response() { Code = 400, Message = "Su sesión expiro, por favor ingrese de nuevo" });

            if (data == null)
                return Json(new Response() { Code = (int)UtilidadesBLL.EstadoAplicacion.ServerError, Message = "Bad request" });

            if (string.IsNullOrEmpty(data.Password))
                return Json(new Response() { Code = 500, Message = "Contraseña incorrecta." });
            if (data.Password.Length <= 8)
                return Json(new Response() { Code = 500, Message = "Contraseña incorrecta, debe tener mas de 8 caracteres" });
            if (data.Password != data.ValidaPassword)
                return Json(new Response() { Code = 500, Message = "Las contraseñas no coinciden." });

            if(string.IsNullOrEmpty(data.Correo))
                return Json(new Response() { Code = 500, Message = "Correo no válido." });

            if (!UtilidadesBLL.EsCorreoValido(data.Correo))
                return Json(new Response() { Code = 500, Message = "Correo no válido." });


            UsuarioDTO user = Seguridad();

            return Json(new UsuarioBLL().Adicionar(data, user.UsuarioID));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult EditarUsuario(UsuarioDTO data)
        {
            if (Seguridad() == null)
                return Json(new Response() { Code = 400, Message = "Su sesión expiro, por favor ingrese de nuevo" });

            if (data == null)
                return Json(new Response() { Code = (int)UtilidadesBLL.EstadoAplicacion.ServerError, Message = "Bad request" });

            if (data.UsuarioID == 0)
                return Json(new Response() { Code = 500, Message = "Usuario no válido." });

            if (string.IsNullOrEmpty(data.Correo))
                return Json(new Response() { Code = 500, Message = "Correo no válido." });


            UsuarioDTO user = Seguridad();

            return Json(new UsuarioBLL().Editar(data, user.UsuarioID));
        }
    }
}

UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

UI/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>Bici- Inventario</title>

    <meta name="description" content="User login page" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css" />

    <!-- text fonts -->
    <link rel="stylesheet" href="~/assets/css/ace-fonts.css" />

    <!-- ace styles -->
    <link rel="stylesheet" href="~/assets/css/ace.min.css" />
    <link rel="stylesheet" href="~/assets/css/ace-rtl.min.css" />

    <!--[if lte IE 9]>
      <link rel="stylesheet" href="../assets/css/ace-ie.min.css" />
    <![endif]-->
    <link rel="stylesheet" href="~/assets/css/ace.onpage-help.css" />
</head>

<body class="login-layout light-login">
    <script type="text/javascript">
        window.jQuery || document.write("<script src='../assets/js/jquery.min.js'>" + "<" + "/script>");
    </script>
    <div class="main-container">
        <div class="main-content">
            <div class="row">
                <div class="col-sm-10 col-sm-offset-1">
                    @RenderBody()
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.main-content -->
    </div><!-- /.main-container -->
    <!-- basic scripts -->
    <!--[if !IE]> -->

    <script type="text/javascript">
        if ('ontouchstart' in document.documentElement) document.write("<script src='../assets/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
    </script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/ace-elements.min.js"></script>
    <script src="~/assets/js/ace.min.js"></script>
    <script type="text/javascript" src="~/Scripts/Inventario.js"></script>



    <!-- inline scripts related to this page -->
    <script type="text/javascript">
		jQuery(function($) {
			    $(document).on('click', '.toolbar a[data-target]', function(e) {
				e.preventDefault();
				var target = $(this).data('target');
				$('.widget-box.visible').removeClass('visible');//hide others
				$(target).addClass('visible');//show target
			    });
        });

        ///Retorna el token de validacion de MVC
        function gettoken() {
            var token = '@Html.AntiForgeryToken()';
            token = $(token).val();
            return token;
        }
    </script>
</body>
</html>

UI/Views/Shared/_Master.cshtml
@using DTO;
@{
    UsuarioDTO usuario = new UsuarioDTO();
    try
    {
        usuario = (UsuarioDTO)Session["user"];
    }
    catch (Exception ex)
    {

    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>Bici-Inventario</title>

    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css" />

    <!-- page specific plugin styles -->
    <!-- text fonts -->
    <link rel="stylesheet" href="~/assets/css/ace-fonts.css" />

    <!-- ace styles -->
    <link rel="stylesheet" href="~/assets/css/ace.min.css" id="main-ace-style" />


    <link rel="stylesheet" href="~/assets/css/ace-skins.min.css" />
    <link rel="stylesheet" href="~/assets/css/ace-rtl.min.css" />
    <script src="~/assets/js/ace-extra.min.js"></script>
    <script src="~/assets/js/jquery.min.js"></script>
    <script type="text/javascript" src="~/Scripts/Inventario.js"></script>
    <script type="text/javascript">

        function gettoken() {
            var token = '@Html.AntiForgeryToken()';
            token = $(token).val();
            return token;
        }
    </script>
</head>

<body class="no-skin">
    <!-- #section:basics/navbar.layout -->
    <div id="navbar" class="navbar navbar-default">
        <script type="text/javascript">
            try { ace.settings.check('navbar', 'fixed') } catch (e) { }
        </script>

        <div class="navbar-container" id="navbar-container">
            <!-- #section:basics/sidebar.mobile.toggle -->
            <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler">
                <span class="sr-only">Toggle sidebar</span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>
            </button>

            <!-- /section:basics/sidebar.mobile.toggle -->
            <div class="navbar-header pull-left">
                <!-- #section:basics/navbar.layout.brand -->
                <a href="#" class="navbar-brand">
                    <small>
                        Bici Inventario
                    </small>
                </a>
            </div>

            <!-- #section:basics/navbar.dropdown -->
            <div class="navbar-buttons navbar-header pull-right" role="navigation">
                <ul class="nav ace-nav">
                    <li class="light-blue">
                        <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                            <img class="nav-user-photo" src="~/assets/avatars/user.jpg" alt="Jason's Photo" />
                            <span class="user-info">
                                <small>Bienvenido,</small>
                                @usuario.Nombres
                            </span>

                            <i class="ace-icon fa fa-caret-down"></i>
                        </a>

                        <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                            <li>
                                <a href="@Url.Action("Perfil","Login")">
                                    <i class="ace-icon fa fa-user"></i>
                                    Mi perfil
                                </a>
                            </li>

                            <li class="divider"></li>

                            <li>
                                <a href="@Url.Action("LogOut","Login")">
                                    <i class="ace-icon fa fa-power-off"></i>
                                    Cerrar Sesión
                                </a>
                            </li>
                        </ul>
                    </li>

                    <!-- /section:basics/navbar.user_menu -->
                </ul>
            </div>

            <!-- /section:basics/navbar.dropdown -->
        </div><!-- /.navbar-container -->
    </div>

    <!-- /section:basics/navbar.layout -->
    <div class="main-container" id="main-container">
        <script type="text/javascript">
            try { ace.settings.check('main-container', 'fixed') } catch (e) { }
        </script>

        <!-- #section:basics/sidebar -->
        <div id="sidebar" class="sidebar                  responsive">
            <script type="text/javascript">
                try { ace.settings.check('sidebar', 'fixed') } catch (e) { }
            </script>


            <ul class="nav nav-list">
                <li class="">
                    <a href="@Url.Action("Dashboard","Reporte")">
                        <i class="menu-icon fa fa-tachometer"></i>
                        <span class="menu-text"> Dashboard </span>
                    </a>

                    <b class="arrow"></b>
                </li>
                <li class="">
                    <a href="@Url.Action("Index","Usuario")">
                        <i class="menu-icon fa fa-user"></i>
                        <span class="menu-text"> Usuarios </span>
                    </a>

                    <b class="arrow"></b>
                </li>
                <li class="">
                    <a href="@Url.Action("Index","Material")">
                        <i class="menu-icon fa fa-list"></i>
                        <span class="menu-text"> Materiales </span>
                    </a>
                    <b class="arrow"></b>
                </li>
                <li class="">
                    <a href="@Url.Action("Index","Inventario")">
                        <i class="menu-icon fa fa-info"></i>
                        <span class="menu-text"> Inventario </span>
                    </a>
                    <b class="arrow"></b>
                </li>
                <li class="">
                    <a href="@Url.Action("Index","Reporte")">
                        <i class="menu-icon fa fa-info"></i>
                        <span class="menu-text"> Reporte </span>
                    </a>
                    <b class="arrow"></b>
                </li>
            </ul><!-- /.nav-list -->
            <!-- #section:basics/sidebar.layout.minimize -->
            <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
                <i class="ace-icon fa fa-angle-double-left" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
            </div>

            <!-- /section:basics/sidebar.layout.minimize -->
            <script type="text/javascript">
                try { ace.settings.check('sidebar', 'collapsed') } catch (e) { }
            </script>
        </div>

        <!-- /section:basics/sidebar -->
        <div class="main-content">
            <!-- #section:basics/content.breadcrumbs -->
            <div class="breadcrumbs" id="breadcrumbs">
                <script type="text/javascript">
                    try { ace.settings.check('breadcrumbs', 'fixed') } catch (e) { }
                </script>


            </div>

            <div class="page-content">
                @RenderBody()
            </div><!-- /.page-content -->
        </div><!-- /.main-content -->

        <div class="footer">
            <div class="footer-inner">
                <!-- #section:basics/footer -->
                <div class="footer-content">
                    <span class="bigger-120">
                        <span class="blue bolder">Bici</span>
                        Inventario &copy; @DateTime.Now.Year
                    </span>

                </div>

                <!-- /section:basics/footer -->
            </div>
        </div>

        <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
            <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
        </a>
    </div><!-- /.main-container -->

   

    <script type="text/javascript">
        if ('ontouchstart' in document.documentElement) document.write("<script src='~/assets/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
    </script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/jquery.dataTables.min.js"></script>
    <script src="~/assets/js/jquery.dataTables.bootstrap.js"></script>
    <script src="~/assets/js/ace-elements.min.js"></script>
    <script src="~/assets/js/ace.min.js"></script>
   

    <link rel="stylesheet" href="~/assets/css/ace.onpage-help.css" />
    <link rel="stylesheet" href="~/docs/assets/js/themes/sunburst.css" />

    <script type="text/javascript">ace.vars['base'] = '..';</script>
    <script src="~/assets/js/ace/elements.onpage-help.js"></script>
    <script src="~/assets/js/ace/ace.onpage-help.js"></script>
    <script src="~/docs/assets/js/rainbow.js"></script>
    <script src="~/docs/assets/js/language/generic.js"></script>
    <script src="~/docs/assets/js/language/html.js"></script>
    <script src="~/docs/assets/js/language/css.js"></script>
    <script src="~/docs/assets/js/language/javascript.js"></script>


    <script type="text/javascript">

        $(document).ready(function () {
            $('.datatable').DataTable({
            });

        });


    </script>

</body>
</html>